[simulation]
moleculename = "6SZF" # MOLECULE NAME
folder = "Result"
sequence = "DAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIA" # INPUT SEQUENCE
interface = "openmm" # INTERFACE TO OPENMM (OpenMM Should be installed from https://openmm.org/
n_samples = 1000 # Number of Samples (This divides the timesteps into segments)
md_simulation = 10 # Top-N Samples for md simulation
temp = 300.0 # equilibration temperature.
forcefield = [
    "amber14-all.xml",
    "amber14/tip3p.xml",
] # Force Field specification
device = "CUDA" # Device to run MD simulation
solvent = 5000 # Solvation
steps = 500 # Equlibration timesteps (uses Langevin Integrator from OpenMM)
gamma = 1.0 # Friction coefficient
dt = 0.01 # Integrator timestep
md_steps = 10 # MD timestep
method = "search" # Adaptive Sampling
