[simulation]
moleculename = "6X7I"
folder = "Result"
sequence = "GQERFNRWFLTGMTVAGVVLLGSLFSRK"
interface = "openmm"
n_samples = 100
md_simulation = 10
temp = 300.0
forcefield = ["amber14-all.xml", "amber14/tip3p.xml"]
device = "CPU"
solvent = 100
steps = 5000
gamma = 1.0
dt = 0.002
md_steps = 1000
method = "fold"
