[simulation]
moleculename = "6X7I"
folder = "Result"
sequence = "GQERFNRWFLTGMTVAGVVLLGSLFSRK"
interface = "openmm"
n_samples = 2048
md_simulation = 20
temp = 300.0
forcefield = ["amber14-all.xml", "amber14/tip3p.xml"]
device = "CUDA"
solvent = 10000
steps = 500000
gamma = 1.0
dt = 0.002
md_steps = 100000
method = "fold"
