[simulation]
moleculename = "6RRO" # MOLECULE NAME
folder = "Result"
sequence = "GFIV" # INPUT SEQUENCE
interface = "openmm" # INTERFACE TO OPENMM (OpenMM Should be installed from https://openmm.org/
n_samples = 100 # Number of Samples (This divides the timesteps into segments)
md_simulation = 10 # Top-N Samples for md simulation
temp = 300.0 # equilibration temperature.
forcefield = [
    "amber14-all.xml",
    "amber14/tip3p.xml",
] # Force Field specification
device = "CPU" # Device to run MD simulation
solvent = 10 # Solvation
steps = 50 # Equlibration timesteps (uses Langevin Integrator from OpenMM)
gamma = 1.0 # Friction coefficient
dt = 0.002 # Integrator timestep
md_steps = 1 # MD timestep
method = "fold" # Adaptive Sampling
