[simulation]
moleculename = "6RRO"
folder = "Result"
sequence = "GFIVKRFKILV"
interface = "openmm"
n_samples = 2048
md_simulation = 10
sample_top_n = 10
temp = 300.0
forcefield = ["amber14-all.xml", "amber14/tip3p.xml"]
device = "CUDA"
solvent = 100
steps = 5000
gamma = 1.0
dt = 0.002
md_steps = 1000
method = "fold"
