[package]
name = "libdncs"
version = "0.1.3"
edition = "2021"

[dependencies]
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
regex = "1.10.5"
