name: dncs-release
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: armv7-unknown-linux-musleabi
            os: ubuntu-latest
          - target: riscv64gc-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.83.0
        with:
          target: ${{ matrix.target }}

      - name: Run Cargo Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: create artifact directory
        shell: bash
        run: |
          directory=dncs-${{ matrix.target }}
          mkdir $directory
          cp README.md LICENSE NOTICE $directory
          if [ -f target/${{ matrix.target }}/release/dncs.exe ]; then
            cp target/${{ matrix.target }}/release/dncs.exe $directory
            7z a -r $directory.zip $directory
          else
            cp target/${{ matrix.target }}/release/dncs $directory
            tar cJf $directory.tar.xz $directory
          fi

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: dncs-${{ matrix.target }}
          path: "dncs-${{ matrix.target }}.*"
          retention-days: 3

      - uses: ncipollo/release-action@v1.14.0
        if: github.event_name == 'release'
        with:
          artifacts: "dncs-${{ matrix.target }}.*"
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
