name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            arch: x86_64
            artifact_name: linux
            asset_name: dncs-linux-x86_64
          - os: ubuntu-latest
            arch: aarch64
            artifact_name: linux
            asset_name: dncs-linux-aarch64
          - os: windows-latest
            arch: x86_64
            artifact_name: windows
            asset_name: dncs-windows-x86_64.exe
          - os: windows-latest
            arch: aarch64
            artifact_name: windows
            asset_name: dncs-windows-aarch64.exe
          - os: macos-latest
            arch: x86_64
            artifact_name: macos
            asset_name: dncs-macos-x86_64
          - os: macos-latest
            arch: aarch64
            artifact_name: macos
            asset_name: dncs-macos-aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch }}-unknown-${{ matrix.os == 'windows-latest' && 'windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}

      - name: Build
        run: cargo build --release --target ${{ matrix.arch }}-unknown-${{ matrix.os == 'windows-latest' && 'windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}

      - name: Rename binary
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.arch }}-unknown-windows-msvc/release/dncs.exe ${{ matrix.asset_name }}
          else
            cp target/${{ matrix.arch }}-unknown-${{ matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}/release/dncs ${{ matrix.asset_name }}
          fi

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
